### ISSUE TITLE
categories/types of documents 

### ISSUE THREAD

**Issue by spencer-hong** [furkanbiten/idl_data#3]
Hi,

thanks for making this dataset available. In the paper, there were metadata analyses about the types of documents, but I couldn't locate that metadata in the data dump. Where is this located?

**Comment by furkanbiten** [comment]
Hello @spencer-hong,

You are welcome 🤗 

The link is this: https://www.industrydocumentslibrary.ucsf.edu/dataset
You can download the metadata by folder structure or by collection. 

That link is located in here: https://www.industrydocuments.ucsf.edu/research-tools/api/

**Comment by furkanbiten** [comment]
Closing the issue now, reopen if it does not solve your problem @spencer-hong.

**Comment by spencer-hong** [comment]
hi @furkanbiten, thanks for getting back to me. I replicated the sql server from IDL, and had thought that the field "document category" in the schema would have been where I could have found this information, but turns out "document_category" just refers to public, privileged, missing or confidential. 

Could you point out exactly where in the SQL schema the types of documents are located?

**Comment by furkanbiten** [comment]
Hi @spencer-hong ,

I have used the Dataset_by_collection folder. Inside that, you will find all the csv files. 
Each csv file has all the file names and the category type inside it. 
We used csv files to exract category information.

**Comment by spencer-hong** [comment]
Thanks so much!
