### ISSUE TITLE
Mapping OCR dataset to RVL-CDIP

### ISSUE THREAD

**Issue by PavlosFragkogiannisTR** [furkanbiten/idl_data#6]
Hi,

thanks for making this dataset available. I understand there's an overlap between this OCR dataset (IDL) and the RVL-CDIP dataset (IIT-CDIP), and some collections are shared. However, I was wondering:

1. Is there a way to find which collections of this dataset (and therefore of IDL) are also part of RVL-CDIP? I couldn't find this exact information in the RVL-CDIP [original paper](https://arxiv.org/pdf/1502.07058.pdf).
2. Assuming we could find the overlapping collections, are you aware of any unique identifier that both datasets have, which we could use to map the OCR data into the existing different splits of the (pre-split) RVL-CDIP dataset?

**Comment by Mohamed-Dhouib** [comment]
Hello , Did you find a way to do this ?
@furkanbiten I think this work can be even more useful if a direct map between the annotations and the RVL-CDIP is provided.

**Comment by PavlosFragkogiannisTR** [comment]
@Dhouib-med not really..

**Comment by furkanbiten** [comment]
@rubenpt91 has done it, maybe he can dig up his some old code to help you guys out.

**Comment by Mohamed-Dhouib** [comment]
@rubenpt91 it will be great if you can direct us in the good direction !

**Comment by rubenpt91** [comment]
Hi @Dhouib-med ,  @PavlosFragkogiannisTR , I have done the mapping between OCR-IDL and RVL-CDIP with the id and iit_id fields in the Collections metadata. It took me some time, but I have uploaded a json file with the format:
```
[
     {'idl_id': 'ffbb0000',  'iit_id': 'klg00a00',  'collection': 'Council_for_Tobacco_Research_Records.csv', 'is_in_rvl_cdip': False},
     {'idl_id': 'ffbb0001',  'iit_id': 'bkz03a00',  'collection': 'RJ_Reynolds_Records_9.csv', 'is_in_rvl_cdip': False}
     ...
]
```
You can find it [here](https://datasets.cvc.uab.es/UCSF_IDL/ocr_idl_ids.json)

I guess this will solve your problem. If you need anything else please let use know

**Comment by Mohamed-Dhouib** [comment]
@rubenpt91 thanks this is really helpful !

**Comment by furkanbiten** [comment]
Big thanks to @rubenpt91! 🤗

**Comment by Mohamed-Dhouib** [comment]
@rubenpt91 Thanks for the link but I can't find the idl_id and the iit_id in the file you uploaded !

**Comment by rubenpt91** [comment]
Sorry @Mohamed-Dhouib, I recently moved the file to a server and messed up the links. Here is the correct [link](https://datasets.cvc.uab.es/UCSF_IDL/ocr_idl_ids.json) to get the file with the IDs (I also have updated the previous comment with the correct link).
