### ISSUE TITLE
Issue with untaring .02 files

### ISSUE THREAD

**Issue by PavlosFragkogiannisTR** [furkanbiten/idl_data#7]
Hi,

thanks for making this dataset available. I am trying to download the compressed files and extract their contents. I have had success doing it for the 5 ".01" files, specifically the following files:

- http://datasets.cvc.uab.es/UCSF_IDL/OCR/f.tar.gz.01
- http://datasets.cvc.uab.es/UCSF_IDL/OCR/g.tar.gz.01
- http://datasets.cvc.uab.es/UCSF_IDL/OCR/h.tar.gz.01
- http://datasets.cvc.uab.es/UCSF_IDL/OCR/j.tar.gz.01
- http://datasets.cvc.uab.es/UCSF_IDL/OCR/k.tar.gz.01

The command I used was simply a tar command for .gzip files, specifically this:

`tar -xzf f.tar.gz.01`

However, it doesn't seem to be working when trying for the ".02" files. I've tried with 4 of them (f.tar.gz.02, h.tar.gz.02, j.tar.gz.02, k.tar.gz.02) but all I'm getting is the following error:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/91783812/225717688-464e39ac-5a19-4118-b70c-ae4a3460cdb2.png">

I've also tried without the "z" flag (i.e., assuming they're not .gzip compressed files) but I'm getting different error messages. Is there something I'm doing wrong? We really need to use the additional data as some more rare document classes (e.g., "resume") require that in order to get a sufficient number of documents from those classes. Thank you.

**Comment by furkanbiten** [comment]
Hi @PavlosFragkogiannisTR,

If I am not mistaken, you should only run the command for the `tar.gz.01`. 
Tar will automatically find the `02, 03, 04, ...`.

So, having run `tar xzf f.tar.gz.01` will untar all the files for `f`.
